### ISSUE TITLE
small display edit to the mosaic preview

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#144]
I was using the optical mosaic preview yesterday and I was few questions: 

- could it be possible to add some margin after the icons on the bottom of the preview?
![Capture d’écran 2021-12-01 à 09 01 38](https://user-images.githubusercontent.com/12596392/144195066-bf77368a-9410-4680-80f4-1af8590759d6.png)

- Is it normal that preview never use the same popup window size ? On the following example L8 preview is longer that my screen heigh and the 2 others are L7, one being big and the other small but I don't understand why
![Capture d’écran 2021-12-01 à 09 03 09](https://user-images.githubusercontent.com/12596392/144195325-3bd6c56a-ac19-4790-9974-b63d80c57240.png)
![Capture d’écran 2021-12-01 à 09 02 53](https://user-images.githubusercontent.com/12596392/144195181-500c68d7-6492-4cf9-af3f-fc9b5cd17855.png)
![Capture d’écran 2021-12-01 à 09 02 59](https://user-images.githubusercontent.com/12596392/144195228-8f4b2c19-60f1-4e1c-98f0-683ad47c6d0c.png)

**Comment by cdanielw** [comment]
We'll check out the margin. 

Preview size - that's the size we get from USGS and ESA. We just take them as they are. We could limit the size to the smallest of the previews, to make this consistent. But then we'd loose out on the ability to take advantage of the larger previews. That last one though - the details need to fit on the screen, so that's something we need to look at.

**Comment by cdanielw** [comment]
Fixed on master.
