### ISSUE TITLE
add a reset password btn to the user admin section

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#158]
## Current workflow

It happens all the time in webinars with very green users. They register to SEPAL, and in GEE and in NICFI, and in many other programs, and at some point they lose track of which email address they used for which program. In the second session of their webinar when they try to reconnect, they don't remember their email and thus cannot fill the "forget password" form. 

As they don't want to make any effort (let's be honest) they fill the registration form again and again and again.....

From the admin perspective, we of course cannot add them again as they already have an account. So we open a new tab in incognito mode, copy-paste their email and fill the "forget password" form for them. This was first demonstrated to me by @yfinegold and I think she agrees when I say: it takes too much time (because they come to you in packs).

I agree that they should use the same email or at least remember it in the first place but that will be more difficult to change human behavior than SEPAL code ;-)  

## possible solution

Could it be possible to add a "send reset password" button in the admin section? So that admin can simply look for the user in the table and click on the button to send the reset email.

Something like this: 
![Capture d’écran 2021-12-10 à 08 18 33](https://user-images.githubusercontent.com/12596392/145533781-76423e44-df1a-41f4-bec3-023a0bc4bdb4.png)

**Comment by cdanielw** [comment]
Sounds reasonable to me.

**Comment by eriklindquist** [comment]
Dears...just a little bit about all this. We have known for a long time that the user management part of SEPAL is not the greatest and we do have these issues. For a long time, we have simply put these user management issues lower down on the priority list in favor of geospatial functionality. I am happy to know some of these issues will get fixed. But, if we have time to prioritize user management, then I think we should take a minute, decide what else we need in this section, and then get it all in one go rather than through individual issues. Is there time to work on SEPAL user management? If so, then let's discuss.

I just don't want anyone to think that these are necessarily new issues or that they have not been discussed before.

Erik

Erik Lindquist, PhD
Forestry Officer
Forestry Division
Food and Agriculture Organization of the United Nations
Rome, Italy 00153
________________________________

**Comment by 12rambau** [comment]
@eriklindquist as this button will be useful anyway I'd like to leave it open. Do you want to open another thread for the user management ? (or maybe there is already one)

**Comment by lpaolini** [comment]
Done, it's committed to master.

**Comment by 12rambau** [comment]
actually, there is an already existing channel:  https://github.com/openforis/sepal/issues/119
