### ISSUE TITLE
the name of the folder is not changed when the name of the recipe is changed

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#194]
**Describe the bug**
when you dynamically change the name of your recipe in the tab name the folder name where the file will be saved is not edited. 

**To Reproduce**
Go to a new recipe (e.g time series) call it "toto". fill all the necessary field to get to the download step. 
The folder will be named : "downloads/toto".

Without living the download window, change the recipe name for "tutu". The download folders is still called "downloads/toto". 

**Expected behavior**

1. the textfield is always edited even if I don't close the download window
2. maintain the current way but force close the all the menus on the map when I edit the recipe name

**Screenshots**
![image](https://user-images.githubusercontent.com/12596392/179458582-bbaa7c3b-f608-4230-bafa-7c632949b640.png)

**Comment by cdanielw** [comment]
Your default path will change when renaming a recipe as long as you haven't already retrieved that recipe and haven't reloaded the page since. 

Once a recipe has been retrieved, the path should not automatically change when renaming a recipe. You might already have selected a custom path, or already retrieved data to the previous default path that you want to append to (we're introducing strategies on how to deal with preexisting exports). We currently don't persist the retrieve form options, so reloading the page will give you a path matching your recipe name. What we probably should do is to start persisting these retrieve options. Quite the opposite to what you're asking for here - sorry! :-).

**Comment by 12rambau** [comment]
no worries, I'm not particularly kin on solution 1. (I'm simply passing a request from a user). The main thing here is that  there are 2 behavior coexisting. I am more into solution 2. which leads to change nothing from your side but prevent user to change the title of the tabl while something else is open (and vice-versa)
