### ISSUE TITLE
Jupyter lab is somehow out of date and needs to be 'built'.

### ISSUE THREAD

**Issue by eriklindquist** [openforis/sepal#99]
I have been opening the jupyter lab, and I get the error to "Build jupyter lab", however when I try to build, I get the following error.

 

Build Failed

Build failed with 500, please run 'jupyter lab build' on the server for full output

 

On cmd I get the following error "permission denied."

 

An error occurred.

PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/lab/staging/index.js'

See the log file for details:  /tmp/jupyterlab-debug-5nsho_t3.log

 

This is causing difficulties in accessing some of the jupyterlab extensions i.e  jupyter-leaflet for interactive mapping with gee in jupyterlab.

**Comment by 12rambau** [comment]
Yep It starting less than a week ago and me, @ingdanielguerrero and @BuddyVolly have moved back to Jupyter Notebook when we want to see our maps.... 

Alternatively, you can use the `voila` preview button, it will open a side panel with the map. 

Regarding the issue here, it is clearly related to #78 and #57 that actually corrected themselves via rebuild of the Jupyter layer.

**Comment by 12rambau** [comment]
The last build (10/06/2021) solved the issue

I have the filling that the problem is linked to the update of jupyterlab and python libraries. The update of `requirement.txt` trigger the new build but as the jupyter layer doesn't change it stays the same, becoming out of synch with the currently installed python libs.

I'll check if there would be a way to rebuild jupyterlab without rebuilding all the layers
